// <auto-generated />
namespace Cars.Web.Database.DomainMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class FirstInitialisation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstInitialisation));
        
        string IMigrationMetadata.Id
        {
            get { return "201406081216020_FirstInitialisation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
